### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bbenne10** [pfalcon/picotui#2]
What is the license for this library? I am intending to fork (I love the ideas, but want to implement some changes and am not sure if they're micropython compatible). I want to make sure that my fork is properly licensed. 

OR we can discuss adding some of the changes I'm interested in. For instance, adding width and height variables for the controlling terminal as properties on a Screen instance, adding a setup.py (which may or may not help you out overall) and chaging `init_tty` and `deinit_tty` (and various accoutrements) to work as a context manager.

**Comment by pfalcon** [comment]
I've added MIT license.

> For instance, adding width and height variables for the controlling terminal as properties on a Screen instance, adding a setup.py (which may or may not help you out overall) and chaging init_tty and deinit_tty (and various accoutrements) to work as a context manager.

I'm not interested in adding syntactic sugar for already high-level framework whose aim is to be unbloated. I encourage contributions along the main scope of the project, which is adding useful widgets, and of course bug and issue fixes (which are a lot). Thanks.
