### ISSUE TITLE
add __index__.py

### ISSUE THREAD

**Issue by fiee** [pfalcon/picotui#27]
Please add an (empty)` __index__.py` to the module folder, otherwise it doesn’t work as a module (at least not installed as an egg).

**Comment by pfalcon** [comment]
Not a known issue. You would need to elaborate how to reproduce it.

**Comment by fiee** [comment]
Is checked out this repo and installed it with `python setup.py install` into a virtual environment.
The egg is installed in the venv’s site_packages. Python can’t find it if I try to import. As soon as I add the `__init__.py`, it works.

Python.org’s CPython 3.6 on OSX 10.9.5

**Comment by pfalcon** [comment]
Ok, I see the problem. picotui relies on a modern "namespace package" feature of Python3, but there's some baggage with how namespace packages are handled by setuptools: https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package .

Given that how it's used by picotui, it's actually a real package, not a namespace package (i.e. a collection of namespaced modules), I'll add `__init__.py` as the quickest fix.

**Comment by pfalcon** [comment]
Fixed in 42a4a6be42f56fb7924c5ce76cba43cd63c4bea1. Thanks for report.
