### ISSUE TITLE
Release 1.0 preparation

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/picotui#29]
I guess there were enough changes, and I believe I applied all breaking changes I had in my so far.

So, I'd be ready to make the 1.0 release soon after leave some room for additional testing.

@peterjschroeder , @fiee: Let me know if you'd be interested to test the latest master. (I address to you because you submitted for than one ticket to the project. Feel free to ignore if you aren't interested/too busy.) Thanks.

**Comment by peterjschroeder** [comment]
I can test sometime later today. I'd have to merge with my color branch as my app depends on it.

**Comment by pfalcon** [comment]
@peterjschroeder : Thanks, if you have time/interest for it. There's no (big) hurry, I'd say next weekend as the target release date sounds good to me.

**Comment by peterjschroeder** [comment]
Tested, everything in my app is still working as intended. I had to make some changes to my colors branch to work with it tho. Maybe at some point you can pull that in.

**Comment by pfalcon** [comment]
@peterjschroeder: Thanks for testing! I hope to make the release on weekend then.

> my colors branch to work with it tho. Maybe at some point you can pull that in.

Yes, I remember about it. As you can see, I'm so far still dealing with technical debt on my side, and then would like to understand usecase for color features better. Sorry if it can take more time still. In the meantime, you know what to do - that's exactly what you do: if this project is useful to you, but you need more, you can add features on your side, and sharing them as a pull request is definitely helpful for me as a maintainer to understand better how people use the lib, and may be useful to other picotui users too. Thanks!

**Comment by peterjschroeder** [comment]
You're welcome.

No problem. It is not hard to maintain the branch, but I think other's would find it useful. The widget colors are currently hardcoded into the library, which is fine for a uniform look between applications. But some application developers may want to use their own colors without modifying the library. I am one of those. To the end-user, a better way to do it is to set the colors from a config file (.picotuirc or something similar). My changes are good enough for now, but I may look into adding the config file later.

**Comment by fiee** [comment]
Hi, thanks for the invitation and sorry for being late, I’m quite swamped ATM.

I just have one little app yet that uses picotui, but I started a configuration driven "design" approach, see https://github.com/fiee/picotui/tree/master/piconf

I’ll update to your latest changes soon and I’ll try to integrate color setup.

**Comment by pfalcon** [comment]
> I’m quite swamped ATM.

Same here, that's I wanted to package the result of last 2 months of refactoring as 1.0, so people didn't play with an older, now incompatible release. Perhaps, there're chances for more refactoring, maybe even some incompatible cleanups could have been made, to avoid further breaking changes in the next releases - but well, the code should be in much better shape already, and perfectalization can be left for later.

So, the release is made: https://pypi.python.org/pypi/picotui/1.0 , thanks everyone for testing!

For reference, incompatible changes in this release are tracked as https://github.com/pfalcon/picotui/issues?utf8=%E2%9C%93&q=label%3A%22breaking+change%22+1.0.
