### ISSUE TITLE
Will this toolkit work on MicroPython?

### ISSUE THREAD

**Issue by amotl** [pfalcon/picotui#35]
Dear Paul,

maybe we missed that detail from the documentation, so please bear with us.

We are humbly asking if this widget toolkit will actually work on embedded devices? Currently, we are trying to invoke it on the most recent Pycom firmware based on MicroPython 1.11
```
Pycom MicroPython 1.20.1.r[v1.11-3138a13] on 2019-10-08; FiPy with ESP32
```

but we are receiving
```
>>> from picotui.context import Context
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "picotui/context.py", line 1, in <module>
  File "picotui/screen.py", line 2, in <module>
ImportError: no module named 'signal'
```

Likewise, the [`signal`](https://github.com/pfalcon/pycopy-lib/tree/master/signal) module will depend on the `ffilib` module.

So, we conclude there probably aren't any chances to run this on neither Pycom MicroPython nor Vanilla MicroPython but only on Pycopy?

Thanks already for taking the time to answer our question revolving this. We would really love to get the spirit of TurboVision to our REPL for being able give [1] a convenient leightweight configuration interface without having to resort to a web-based configuration using a captive portal, which would be rather more heavyweight.

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/hiveeyes-micropython-firmware

**Comment by pfalcon** [comment]
This project is intended to work with Pycopy unix port and CPython. It would work with any other compatible Python implementation. Sadly, I don't have resources to vet other implementations for compatibility with Picotui, or support them.

**Comment by amotl** [comment]
Dear Paul,

we made `picotui` work on MicroPython using some code from @robert-hh within #36.

With kind regards,
Andreas.
