### ISSUE TITLE
TextEntry: Arrow keys add characters, backspace moves entry (cyan) background

### ISSUE THREAD

**Issue by msimonelli331** [pfalcon/picotui#40]
Instead of moving the cursor when pressing the arrow keys it add characters to the input box. Left: D, Up: A, Right: C, Down: B. Backspace just moves the blue background backwards and the cursor forwards.

This was seen running inside a Alpine 3.11 container running Python 3.8.2 and picotui 1.0.1

**Comment by pfalcon** [comment]
This points to unexpected escape sequences produced by the terminal, picotui requires VT100/Xterm terminal.

Information provided is not enough to exactly reproduce the issue, feel free to provide exact step by step instructions, I might look into it.

**Comment by pfalcon** [comment]
No response - closing.
