### ISSUE TITLE
Doesn't run on Windows 10, termios missing

### ISSUE THREAD

**Issue by mijenner** [pfalcon/picotui#41]
I just installed picotui using "pip install picotui". 

Next, trying to run one of the examples I get: 

$ python example_widgets.py 
Traceback (most recent call last):
  File "example_widgets.py", line 7, in <module>
    with Context():
  File "C:\Dropbox\python_uv\picotui-master\picotui\context.py", line 11, in __enter__
    Screen.init_tty()
  File "C:\Dropbox\python_uv\picotui-master\picotui\screen.py", line 121, in init_tty
    import tty, termios
  File "C:\Users\mje\AppData\Local\Programs\Python\Python37\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios

Next, trying to fix this issue, 

pip install termios
ERROR: Could not find a version that satisfies the requirement termios (from versions: none)
ERROR: No matching distribution found for termios

Kind regards, 
Michael

**Comment by pfalcon** [comment]
termios is the standard Python module: https://docs.python.org/3/library/termios.html . If your OS doesn't provide it, then it's not compliant to run picotui. I don't use that OS myself, so cannot provide support for it in my own free time. You may want to contact your OS vendor for further info.

**Comment by ibex-are-goats** [comment]
Trying this now with the latest versions of everything, and still getting this error!

```
from termios import *
ModuleNotFoundError: No module named 'termios'
```

```
pip install termios
ERROR: Could not find a version that satisfies the requirement termios (from versions: none)
ERROR: No matching distribution found for termios
```

Maybe this helps: https://bugs.python.org/issue41663
