### ISSUE TITLE
Not all examples in the README are in the examples dir

### ISSUE THREAD

**Issue by stuaxo** [pfalcon/picotui#43]
The README mentions some examples, but their not the same as the files in the examples directory, e.g. example_widgets.py

**Comment by pfalcon** [comment]
Can you mention the part of README which mentions examples which are not mentioned?

**Comment by stuaxo** [comment]
Ooops I was in a meeting when I wrote this so it makes no sense ... !

**Comment by stuaxo** [comment]
OK, double checked - it really makes no sense - closing.

I missed that some examples are in the root, so was looking in the examples dir for them.

**Comment by pfalcon** [comment]
Right, a few examples are provided in the top-level dir where it's hard to miss them and very easy to run (`git clone` followed by `python3 example_foo.py`). But to not turn the top-level dir into a dump, the rest are in the examples/ dir. The whole disposition should be hinted in the README well enough.
