### ISSUE TITLE
Request: packaging

### ISSUE THREAD

**Issue by olaf7** [pfalcon/picotui#58]
This seems to be a very nice option to rapidly develop TUI applications. What I would really like to see is a .deb (Debian) package for especially Raspbian. Is packaging on the to-do list?

**Comment by pfalcon** [comment]
>  Is packaging on the to-do list?

It's actually done in a fully cross-distro way: https://pypi.org/project/picotui/ . `pip3 install picotui`, voila.

Also note that picotui is still experimental library and has some issues which need to be resolved (which may affect API/usage).
