### ISSUE TITLE
Using arrows within WRadioButton list moves to the next widget 

### ISSUE THREAD

**Issue by antonisar** [pfalcon/picotui#6]
Maybe it's configurable but how do I select something in a WRadioButton with the keyboard? Mouse works ok, arrows move to the next widget.

**Comment by pfalcon** [comment]
Yes, it's not implemented. In https://github.com/pfalcon/picotui/pull/5#issuecomment-278729038, @kyleperik expressed interest to work on that.

**Comment by pfalcon** [comment]
This was implemented by https://github.com/pfalcon/picotui/pull/7. I'd say there's still some room for improvement, but the basic feature now works, so closing. Feel free to provide feedback though.
