### ISSUE TITLE
Better variable naming in examples

### ISSUE THREAD

**Issue by lodenrogue** [pfalcon/picotui#60]
I just learned about this project today and I'm going through the examples and having a horrible time tracking what the hell these variables are. I see variables with names like:

```
a, s, d, b
```
I have to constantly backtrack in the code to remember what these obscure names represent. Don't do this. It's a horrible practice and a waste of time.

**Comment by pfalcon** [comment]
Picotui examples are intended to be simple and short, and easy to look thru. Variable naming corresponds to that - it's concise and obvious for such examples. Feel free to provide specific example(s) of where you have hardship with understanding.

**Comment by lodenrogue** [comment]
You should never name variables a single character regardless of the conciseness of the code. Especially in examples that are meant to introduce new users to your framework. They already have enough cognitive load trying to learn something new. They don't need the overhead of remembering what single character variable names represent. 
Remember that code is written for humans to understand not machines. It should be written in such a way that it flows as if one were reading English.

https://readlearncode.com/code-and-stuff/clean-code-variables/

Also the book:
https://books.google.com/books/about/Clean_Code.html?id=hjEFCAAAQBAJ&source=kp_book_description

**Comment by lodenrogue** [comment]
Close as it seems this project is no longer being maintained.
