### ISSUE TITLE
Do widgets support hotkeys ?

### ISSUE THREAD

**Issue by stuaxo** [pfalcon/picotui#72]
This has the look and feel of turbovision from back in the day, which (I think) supported that, but I can't see any info on how to do it ?

**Comment by pfalcon** [comment]
No, I didn't think about those, as Picotui's original usecase was more or less simple UIs, and myself mostly use mouse even with TUIs.

**Comment by stuaxo** [comment]
Thanks, I shall use something else then.

I'm (over engineering) a tool that works in the normal way (when a menu will be fine), but it's to save logs when my computer has a bug with the graphics driver, when that happens I can't navigate a menu sensibly, but I can press a button.
